# Generated by Django 3.2 on 2021-04-06 13:39

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('ID', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Narrator', models.CharField(max_length=100)),
                ('Duration', models.PositiveIntegerField()),
                ('UploadTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('ID', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Duration', models.PositiveIntegerField()),
                ('UploadTime', models.DateTimeField()),
                ('Host', models.CharField(max_length=100)),
                ('Participants', django_mysql.models.ListCharField(models.CharField(max_length=100), blank=True, max_length=1010, null=True, size=10)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('ID', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Duration', models.PositiveIntegerField()),
                ('UploadTime', models.DateTimeField()),
            ],
        ),
    ]
