# Generated by Django 3.2 on 2021-04-06 18:41

import API.forms
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='Duration',
            field=models.PositiveIntegerField(validators=[API.forms.validate_date]),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='UploadTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 0, 11, 30, 297912), validators=[API.forms.validate_date]),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='UploadTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 0, 11, 30, 297912), validators=[API.forms.validate_date]),
        ),
        migrations.AlterField(
            model_name='song',
            name='UploadTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 0, 11, 30, 282291), validators=[API.forms.validate_date]),
        ),
    ]
