# Generated by Django 3.2 on 2021-04-06 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20210407_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='Duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='UploadTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 1, 57, 3, 895602)),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='UploadTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 1, 57, 3, 895602)),
        ),
        migrations.AlterField(
            model_name='song',
            name='UploadTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 1, 57, 3, 895602)),
        ),
    ]
